# Generated by Django 2.0.7 on 2021-10-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211020_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='First_Name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
