# Generated by Django 2.0.7 on 2021-10-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211020_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Home',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
