# Generated by Django 2.0.7 on 2021-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='Home',
        ),
        migrations.AddField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], default='', max_length=60),
        ),
    ]
