# Generated by Django 3.2.8 on 2021-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(default=''),
        ),
    ]
